In [2]:
!pip install d2l==0.17.2

     |████████████████████████████████| 82 kB 500 kB/s 
     |████████████████████████████████| 9.9 MB 15.4 MB/s 
     |████████████████████████████████| 20.1 MB 1.6 MB/s 
     |████████████████████████████████| 11.6 MB 16.3 MB/s 
     |████████████████████████████████| 61 kB 7.6 MB/s 
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.5
    Uninstalling numpy-1.19.5:
      Successfully uninstalled numpy-1.19.5
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: pandas
    Found existing installation: pandas 1.1.5
    Uninstalling pandas-1.1.5:
      Successfully uninstalled pandas-1.1.5
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the p

In [3]:
# Generating the Dataset
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [5]:
# Read the Dataset
def load_array(data_arrays, batch_size, is_train=True):
    """Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [6]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 2.01799   , -0.73956805],
        [-0.13564879, -2.8292959 ],
        [-0.6035262 , -0.35787454],
        [-1.3636179 ,  0.7213613 ],
        [-0.37893134,  0.7724814 ],
        [-0.15707152, -0.4765346 ],
        [ 0.64530706,  0.42386588],
        [ 0.09832685,  1.0663043 ],
        [-0.976987  ,  0.39912334],
        [-0.77074903, -0.12739815]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[10.743737  ],
        [13.551777  ],
        [ 4.2059627 ],
        [-0.9813379 ],
        [ 0.8164442 ],
        [ 5.490321  ],
        [ 4.0655446 ],
        [ 0.77789444],
        [ 0.8921625 ],
        [ 3.08396   ]], dtype=float32)>)

In [7]:
# Defining the Model
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [8]:
# Initializing Model Parameters
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [10]:
# Defining the Loss Function
loss = tf.keras.losses.MeanSquaredError()

In [11]:
# Defining the Optimization Algorithm
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [12]:
# Training
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000213
epoch 2, loss 0.000099
epoch 3, loss 0.000101


In [13]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([ 0.00123727 -0.00020218], shape=(2,), dtype=float32)
error in estimating b [0.00063086]
